@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

LAYOUT_TOP_DOWN

Person(user, Sportsman , "An amateur sportsman who wants to practice his favorite sport with other people")
System(webApp, "Internet Corporation Application", "Allows sportsman to subscribe to corporation, watch incoming events, subscribe and unsubscribe to events")
System(backend, "Corporation Application System", "Store all information about events and sportsmen")
System_Ext(bot, "Chat bot", "The google chat bot in charge to give information about events.")

Rel(user, webApp,"Views incoming events, subscribe and unsubscribe to events")
Rel(webApp, backend,"Gets events information and manage subscription")
Rel(webApp, bot,"Send information using")
Rel(bot, user,"Show information to")

@enduml
